name: generators
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.1.5
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0

flutter: